<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class urlUrlGenerateShortBundleDocumentshortUrlDBHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['fullUrl']) || (! empty($this->class->fieldMappings['fullUrl']['nullable']) && array_key_exists('fullUrl', $data))) {
            $value = $data['fullUrl'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['fullUrl']->setValue($document, $return);
            $hydratedData['fullUrl'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['shortUrl']) || (! empty($this->class->fieldMappings['shortUrl']['nullable']) && array_key_exists('shortUrl', $data))) {
            $value = $data['shortUrl'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['shortUrl']->setValue($document, $return);
            $hydratedData['shortUrl'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nameUrl']) || (! empty($this->class->fieldMappings['nameUrl']['nullable']) && array_key_exists('nameUrl', $data))) {
            $value = $data['nameUrl'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['nameUrl']->setValue($document, $return);
            $hydratedData['nameUrl'] = $return;
        }
        return $hydratedData;
    }
}